version: "3.9"
networks:
    api:
        name: api-network
services:
  api:
    container_name: api_dev
    build: .
    volumes:
      - ./api:/opt/api # map the code so we can take advantage of uvicorn's --reload
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_SCHEMA=public
      - ALLOWED_ORIGIN=http://localhost:3000
      - INIT_DATA_PATH=/opt/data
    ports:
      - "5000:5000"
    networks:
      - api
  db:
    container_name: db
    hostname: db
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - api
    ports:
      - 4321:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.25
    volumes:
      - ${PWD}/setup_files/pgadmin4-servers.json:/tmp/pgadmin4-servers.json:ro
    ports:
      - 5050:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=pgadmin
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_SERVER_JSON_FILE=/tmp/pgadmin4-servers.json
    networks:
      - api
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -s http://pgadmin:5050 > /dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 10s
      retries: 10
